<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pokedex [
<!ELEMENT pokedex (pokemon+)>
<!ELEMENT pokemon (nombre, movimientos, tipos, legendario?)>
  <!ATTLIST pokemon poke_id ID #REQUIRED>
  <!ATTLIST pokemon peso CDATA #REQUIRED>
  <!ATTLIST pokemon gen (primera|segunda|tercera) "primera">
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT movimientos (movimiento+)>
<!ELEMENT movimiento (#PCDATA)>
<!ELEMENT tipos (tipo+)>
<!ELEMENT legendario EMPTY>
<!ENTITY hidro "Hidrobomba">
]>

<pokedex>
  <pokemon poke_id="P160" peso="88.8" gen="segunda">
    <nombre>Feraligtr</nombre>
    <movimientos>
      <movimiento>Triturar</movimiento>
      <movimiento>&hidro;</movimiento>
      <movimiento>Rayo hielo</movimiento>
    </movimientos>
    <tipos>Agua</tipos>
  </pokemon>
  <pokemon poke_id="P146" peso="60">
    <nombre>Moltres</nombre>
    <movimientos>
      <movimiento>Presi√≥n</movimiento>
      <movimiento>Cuerpo Llama</movimiento>
    </movimientos>
    <tipos>
      <tipo>Fuego</tipo>
      <tipo>Volador</tipo>
    </tipos>
    <legendario/>
</pokedex>
